# Install the apt prerequisites
addons:
  apt:
    packages:
      - ruby
      - wget

# We need asciidoctor and exact hugo version
before_install:
  - sudo gem install asciidoctor
  - sudo gem install html-proofer
  - wget https://github.com/gohugoio/hugo/releases/download/v0.30/hugo_0.30_Linux-64bit.deb
  - sudo dpkg -i hugo_0.30_Linux-64bit.deb

# Build the website
script:
  - hugo
  - htmlproofer ./public --external_only --only_4xx